### ISSUE TITLE
Command & Message Limits

### ISSUE THREAD

**Issue by ghostzero** [shardick/twitch-commando#1]
Feature Request: I do not know if it is already supported, but here's an idea from me: It would be cool if the Lib could handle Command & Message limits. So the bot won't be banned as soon as there's a lot of traffic.

Reference: https://dev.twitch.tv/docs/irc/guide/#command--message-limits

**Comment by dowmeister** [comment]
Hi,
it's an interesting request. Commando is not making any check of number of messages sent. 

btw, considering it's an experimental module and a big wip, what do you think about it?

**Comment by dowmeister** [comment]
@ghostzero npm version 1.0.3 includes a basic rate limiting control based on bot types account specifications.

have a look and let me know if you think is a good solution

**Comment by ghostzero** [comment]
@shardick Whoa! Very cool that it has already been implemented :O I will try ASAP when I have the time, I think it's great! :D

**Comment by dowmeister** [comment]
Closing as outdated
