### ISSUE TITLE
Typo found in one of the required flags

### ISSUE THREAD

**Issue by ghost** [shardick/twitch-commando#14]
Typo in one of the flags spotted. Although it does work the required flag is typoed in itself.

```js
client.registerDetaultCommands();
```

should be 

```js
client.registerDefaultCommands();
```

## Version
 - **Twitch-Commando:** `1.0.12`

**Comment by fbramato** [comment]
Hi, i know it's more than 1 year but i didnt looked and worked at this repo until yesterday :)

I've pushed 2.0 with a bunch of changes and fixed some typos \ docs mistake too

**Comment by dowmeister** [comment]
Hi, i know it's more than 1 year but i didnt looked and worked at this repo until yesterday :)

I've pushed 2.0 with a bunch of changes and fixed some typos \ docs mistake too
